const WorldCountries = [
  "Argentina",
  "Brazil",
  "Chile",
  "Colombia",
  "Ecuador",
  "Guyana",
  "Paraguay",
  "Peru",
  "Surinam",
  "Canada",
  "France",
  "United Kingdom",
  "Japan",
  "Spain",
  "India",
  "Germany",
  "Italy",
  "Australia",
  "South Africa",
  "Egypt",
  "Mexico",
  "United States of America",
  "Uruguay",
  /* "Artigas",
  "Canelones",
  "Cerro Largo",
  "Colonia",
  "Durazno",
  "Flores",
  "Florida",
  "Lavalleja",
  "Maldonado",
  "Montevideo",
  "Paysandú",
  "Río Negro",
  "Rivera",
  "Rocha",
  "Salto",
  "San José",
  "Soriano",
  "Tacuarembó",
  "Treinta y Tres", */
];
export default WorldCountries;
