// keywords.js

const categoryKeywords = {
  "Fantasmas y Apariciones": [
    "fantasma",
    "fantasmaa",
    "aparecion",
    "espiritu",
    "espectro",
    "presensia",
    "aparisiones",
    "aparciones",
  ],
  "Leyendas urbanas": [
    "leyenda",
    "leyennda",
    "historia urbana",
    "mito",
    "relato popular",
    "rumor",
    "leyendas",
    "leyendaa",
  ],
  "Lugares Malditos": [
    "cementerio",
    "cementerioo",
    "lugar embrujado",
    "lugar emvrujado",
    "maldicion",
    "maldiccion",
    "sitio maldito",
    "parage",
    "malditoo",
  ],
  "Objetos Malditos": [
    "objeto maldito",
    "obgeto maldito",
    "reliquia",
    "maldicion",
    "amaldito",
    "amuleto",
    "artefato",
    "artfato",
  ],
  "Creencias Sobrenaturales": [
    "hechizo",
    "echizo",
    "brujeria",
    "creencia",
    "supersticion",
    "supersitcion",
    "fe sobrenatural",
    "subernatural",
  ],
  "Juegos y Rituales": [
    "ritual",
    "rituales",
    "juego sobrenatural",
    "invocacion",
    "invokacion",
    "desafio oculto",
    "oculto",
    "ceremonia",
  ],
};

export default categoryKeywords;
